name = input()
surname = input()
animal = input()
sign = input()
print('Индивидуальный гороскоп для пользователя', name, surname)
print('Кем вы были в прошлой жизни:', animal)
print('Ваш знак зодиака -', sign, ', поэтому вы - тонко чувствующая натура.')
